### ISSUE TITLE
Crashes UI tests

### ISSUE THREAD

**Issue by Mair** [okta/okta-sdk-appauth-ios#24]
I set everything up as per the readme file and it works as expected. However, when trying to run SWIFT UI tests, as soon as you click on the login or password field, XCODE crashes

**Comment by jmelberg-okta** [comment]
Hey @Mair! Since the UI tests run against a real Okta org, you'll need to supply user credentials for the test to pass.

First, update the variables [here](https://github.com/okta/okta-sdk-appauth-ios/blob/jm-bug-fixes/Example/Okta_UITests/Okta_UITests.swift#L19-L20) with credentials of a user that belongs to that org. Next, make sure those are copied over [here](https://github.com/okta/okta-sdk-appauth-ios/blob/jm-bug-fixes/Example/Okta_UITests/Okta_UITests.swift#L44-L46).

**Note:** The UI testing has been a bit buggy for me lately. I'm looking into fixing that over the next few weeks.
