### ISSUE TITLE
Invalid_client even right credential & client id?

### ISSUE THREAD

**Issue by gloryluu** [okta/okta-sdk-appauth-ios#29]
`OktaAuth .login()`

> UserInfo={NSLocalizedDescription={"error":"invalid_client","error_description":"Client authentication failed. Either the client or the client credentials are invalid."}}}}

I'm really confuse. I'm sure what I input is right and client id is valid
Later, I tried by harding the email and password phrases, I can login successfully.
`OktaAuth.login(m_email, password: mPassword)`

I dont know why I cannot login by webview.
Anyone can help me?

**Comment by jmelberg-okta** [comment]
Hi @gloryluu,

This is expected behavior. When using the `username` and `password` flow, you need to include it when calling `OktaAuth.login()`. For example:

```swift
OktaAuth
    .login(username: "user@example.com", password: "password")
    .start(view: self) {  response, error in
     ...
}
```

The default `OktaAuth.login()` method is for the [Authorization Code Flow](https://tools.ietf.org/html/rfc6749#section-4.1), where the user will input their credentials via the browser.
